name: mern-app

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mern-app
    ports:
      - "27017:27017"
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    restart: always
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_ENABLED: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_BASIC_AUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_BASIC_AUTH_PASSWORD}
    networks:
      - mern-app
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./server/.env
    networks:
      - mern-app
    ports:
      - "5005:5005"
    volumes:
      - ./server:/app
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - mern-app
    ports:
      - "5173:5173"
    command: npm run dev
    depends_on:
      - api

volumes:
  mongodb-data:
    driver: local
    name: mongo-data
  mongodb-log:
    driver: local
    name: mongo-log

networks:
  mern-app:
    driver: bridge
